name: C tests

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt install -y libncurses5-dev libncursesw5-dev
      - name: make
        run: make
      - name: make test
        run: make test
